const data = {
  'a' : ['charset', 'coords', 'download', 'href', 'hreflang', 'media', 'name', 'ping', 'rel', 'rev', 'shape', 'target', 'type'],
  'abbr' : ['title'],
  'address' : [],
  'applet' : ['align', 'alt', 'archive', 'code', 'codebase', 'height', 'hspace', 'name', 'object', 'vspace', 'width'],
  'area' : ['alt', 'coords', 'download', 'href', 'hreflang', 'media', 'nohref', 'rel', 'shape', 'target'],
  'article' : [],
  'aside' : [],
  'audio' : ['autoplay', 'buffered', 'controls', 'loop', 'muted', 'played', 'preload', 'src', 'volume'],
  'b' : [],
  'base' : ['href', 'target'],
  'basefont' : ['color', 'face', 'size'],
  'bdi' : [],
  'bdo' : [],
  'blockquote' : ['cite'],
  'body' : ['alink', 'background', 'bgcolor', 'link', 'onafterprint', 'onbeforeprint', 'onbeforeunload', 'onhashchange', 'onmessage', 'onoffline', 'ononline', 'onpopstate', 'onredo', 'onstorage', 'onundo', 'onunload', 'text', 'vlink'],
  'br' : ['clear'],
  'button' : ['autofocus', 'disabled', 'form', 'formaction', 'formenctype', 'formmethod', 'formnovalidate', 'formtarget', 'name', 'type', 'value'],
  'canvas' : ['height', 'width'],
  'caption' : [],
  'cite' : [],
  'code' : [],
  'col' : ['align', 'char', 'charoff', 'span', 'valign', 'width'],
  'colgroup' : ['align', 'char', 'charoff', 'span', 'valign', 'width'],
  'content' : ['select'],
  'data' : ['value'],
  'datalist' : [],
  'dd' : [],
  'del' : ['cite', 'datetime'],
  'details' : ['open'],
  'dfn' : [],
  'dir' : ['compact'],
  'div' : [],
  'dl' : ['compact'],
  'dt' : [],
  'element' : [],
  'em' : [],
  'embed' : ['height', 'src', 'type', 'width'],
  'fieldset' : ['disabled', 'form', 'name'],
  'figcaption' : [],
  'figure' : [],
  'font' : ['color', 'face', 'size'],
  'footer' : [],
  'form' : ['accept-charset', 'accept', 'action', 'autocomplete', 'enctype', 'method', 'name', 'novalidate', 'target'],
  'frame' : ['frameborder', 'longdesc', 'marginheight', 'marginwidth', 'name', 'noresize', 'scrolling', 'src'],
  'frameset' : ['cols', 'onunload', 'rows'],
  'h1' : [],
  'h2' : [],
  'h3' : [],
  'h4' : [],
  'h5' : [],
  'h6' : [],
  'head' : ['profile'],
  'header' : [],
  'hr' : [],
  'html' : ['manifest', 'xmlns'],
  'i' : [],
  'iframe' : ['frameborder', 'height', 'longdesc', 'marginheight', 'marginwidth', 'name', 'sandbox', 'scrolling', 'seamless', 'src', 'srcdoc', 'width'],
  'img' : ['src', 'alt', 'width', 'height', 'ismap', 'usemap', 'longdesc'],
  'input' : ['accept', 'alt', 'autocomplete', 'autofocus', 'autosave', 'checked', 'disabled', 'form', 'formaction', 'formenctype', 'formmethod', 'formnovalidate', 'formtarget', 'height', 'inputmode', 'ismap', 'list', 'max', 'maxlength', 'min', 'minlength', 'multiple', 'name', 'pattern', 'placeholder', 'readonly', 'required', 'selectionDirection', 'size', 'spellcheck', 'src', 'step', 'tabindex', 'type', 'usemap', 'value', 'width'],
  'ins' : ['cite', 'datetime'],
  'isindex' : ['prompt'],
  'kbd' : [],
  'keygen' : ['autofocus', 'challenge', 'disabled', 'form', 'keytype', 'name'],
  'label' : ['for', 'form'],
  'legend' : [],
  'li' : ['type', 'value'],
  'link' : ['charset', 'crossorigin', 'href', 'hreflang', 'media', 'rel', 'rev', 'sizes', 'target', 'type'],
  'main' : [],
  'map' : ['name'],
  'mark' : [],
  'menu' : ['compact'],
  'meta' : ['charset', 'content', 'http-equiv', 'name', 'scheme'],
  'meter' : ['value', 'min', 'max', 'low', 'high', 'optimum', 'form'],
  'nav' : [],
  'noframes' : [],
  'noscript' : [],
  'object' : ['align', 'archive', 'border', 'classid', 'codebase', 'codetype', 'data', 'declare', 'form', 'height', 'hspace', 'name', 'standby', 'type', 'typemustmatch', 'usemap', 'vspace', 'width'],
  'ol' : ['compact', 'reversed', 'start', 'type'],
  'optgroup' : ['disabled', 'label'],
  'option' : ['disabled', 'label', 'selected', 'value'],
  'output' : ['for', 'form', 'name'],
  'p' : [],
  'param' : ['name', 'type', 'value', 'valuetype'],
  'picture' : [],
  'pre' : ['width'],
  'progress' : ['max', 'value'],
  'q' : ['cite'],
  'rp' : [],
  'rt' : [],
  'rtc' : [],
  's' : [],
  'samp' : [],
  'script' : ['async', 'charset', 'defer', 'language', 'src', 'type'],
  'section' : [],
  'select' : ['autofocus', 'disabled', 'form', 'multiple', 'name', 'required', 'size'],
  'shadow' : [],
  'small' : [],
  'source' : ['src', 'type'],
  'span' : [],
  'strong' : [],
  'style' : ['disabled', 'media', 'scoped', 'title', 'type'],
  'sub' : [],
  'summary': [],
  'sup' : [],
  'table' : ['align', 'border', 'cellpadding', 'cellspacing', 'frame', 'rules', 'summary', 'width'],
  'tbody' : ['align', 'char', 'charoff', 'valign'],
  'td' : ['abbr', 'align', 'axis', 'char', 'charoff', 'colspan', 'headers', 'height', 'nowrap', 'rowspan', 'scope', 'valign', 'width'],
  'template' : ['content'],
  'textarea' : ['autocomplete', 'autofocus', 'cols', 'disabled', 'form', 'maxlength', 'minlength', 'name', 'placeholder', 'readonly', 'required', 'rows', 'selectionDirection', 'selectionEnd', 'selectionStart', 'spellcheck', 'wrap'],
  'tfoot' : ['align', 'char', 'charoff', 'valign'],
  'th' : ['abbr', 'align', 'axis', 'char', 'charoff', 'colspan', 'headers', 'height', 'nowrap', 'rowspan', 'scope', 'valign', 'width'],
  'thead' : ['align', 'char', 'charoff', 'valign'],
  'time' : ['datetime'],
  'title' : [],
  'tr' : ['align', 'char', 'charoff', 'valign'],
  'track' : ['default', 'kind', 'label', 'src', 'srclang'],
  'u' : [],
  'ul' : ['compact', 'type'],
  'var' : [],
  'video' : ['autoplay', 'autobuffer', 'buffered', 'controls', 'crossorigin', 'height', 'loop', 'muted', 'played', 'preload', 'poster', 'src', 'width'],
  'wbr' : []
}
